@startuml
'https://plantuml.com/activity-diagram-beta

start
:User types in a command to assign something to everyone in the same group;
if () then ([If the required argument prefixes are not provided])
    #pink:Error for missing prefixes is shown to the user;
    kill
([Else]) elseif () then ([If there are duplicate argument prefixes])
    #pink:Error for duplicate prefixes is shown to the user;
    kill
([Else]) elseif () then ([Name of assignment is invalid])
    #pink:Error for invalid name is thrown;
    kill
([Else]) elseif () then ([Score of assignment is not an integer])
    #pink:Error for invalid score is thrown;
    kill
else ([Else])
    #palegreen:Group is parsed;
    #palegreen:Name of assignment is parsed;
    #palegreen:Score of assignment is parsed;
    #palegreen:AssignmentGroup command is returned;
endif
stop
@enduml
