@startuml
scale 4.0
'https://plantuml.com/activity-diagram-beta

start
:User types in a command to assign something to everyone in the same group;

if () then ([If the required argument prefixes are not provided])
      #FF6666:Error for missing prefixes is shown to the user;
      stop
else ([Else])
    if () then (If there are duplicate argument prefixes)
        #FF6666:Error for duplicate prefixes is shown to the user;
        stop
    else ([Else])
        if () then ([Name of assignment is invalid])
            #FF6666:Error for invalid name is thrown;
            stop
        else ([Else])
            if () then ([Score of assignment is not an integer])
                #FF6666:Error for invalid score is thrown;
                stop
            else ([Else])
               #palegreen:Group is parsed;
               #palegreen:Name of assignment is parsed;
               #palegreen:Score of assignment is parsed;
               #palegreen:AssignmentGroup command is returned;
            endif
        endif
    endif
endif

stop
@enduml
