@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":NpcTrackParser" as NpcTrackParser LOGIC_COLOR
participant ":FindGroupCommandParser" as FindGroupCommandParser LOGIC_COLOR
participant "predicate:GroupContainsKeywordsPredicate" as GroupContainsKeywordsPredicate LOGIC_COLOR
participant "name:FindGroupCommand" as FindGroupCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("findGroup tut33")
activate LogicManager

LogicManager -> NpcTrackParser : parseCommand("findGroup tut33")
activate NpcTrackParser

create FindGroupCommandParser
NpcTrackParser -> FindGroupCommandParser
activate FindGroupCommandParser

FindGroupCommandParser --> NpcTrackParser
deactivate FindGroupCommandParser

NpcTrackParser -> FindGroupCommandParser : parse("tut33")
activate FindGroupCommandParser

create GroupContainsKeywordsPredicate
FindGroupCommandParser -> GroupContainsKeywordsPredicate
activate GroupContainsKeywordsPredicate

GroupContainsKeywordsPredicate --> FindGroupCommandParser
deactivate GroupContainsKeywordsPredicate


create FindGroupCommand
FindGroupCommandParser -> FindGroupCommand : FindGroupCommand(predicate)
activate FindGroupCommand

FindGroupCommand --> FindGroupCommandParser : name
deactivate FindGroupCommand

FindGroupCommandParser --> NpcTrackParser : name
deactivate FindGroupCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.`
FindGroupCommandParser -[hidden]-> NpcTrackParser
destroy FindGroupCommandParser

NpcTrackParser --> LogicManager : name
deactivate NpcTrackParser

LogicManager -> FindGroupCommand : execute()
activate FindGroupCommand

FindGroupCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> FindGroupCommand
deactivate Model

create CommandResult
FindGroupCommand -> CommandResult
activate CommandResult

CommandResult --> FindGroupCommand
deactivate CommandResult

FindGroupCommand --> LogicManager : result
deactivate FindGroupCommand

[<--LogicManager
deactivate LogicManager
@enduml
