@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Logic LOGIC_COLOR_T1
participant ":LogicManager" as LogicManager LOGIC_COLOR
participant ":NpcTrackParser" as NpcTrackParser LOGIC_COLOR
participant ":FindCommandParser" as FindCommandParser LOGIC_COLOR
participant "predicate:NameContainsKeywordsPredicate" as NameContainsKeywordsPredicate LOGIC_COLOR
participant "name:FindCommand" as FindCommand LOGIC_COLOR
participant ":CommandResult" as CommandResult LOGIC_COLOR
end box

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
end box

[-> LogicManager : execute("find Edward")
activate LogicManager

LogicManager -> NpcTrackParser : parseCommand("find Edward")
activate NpcTrackParser

create FindCommandParser
NpcTrackParser -> FindCommandParser
activate FindCommandParser

FindCommandParser --> NpcTrackParser
deactivate FindCommandParser

NpcTrackParser -> FindCommandParser : parse("Edward")
activate FindCommandParser

create NameContainsKeywordsPredicate
FindCommandParser -> NameContainsKeywordsPredicate
activate NameContainsKeywordsPredicate

NameContainsKeywordsPredicate --> FindCommandParser
deactivate NameContainsKeywordsPredicate


create FindCommand
FindCommandParser -> FindCommand : FindCommand(predicate)
activate FindCommand

FindCommand --> FindCommandParser : name
deactivate FindCommand

FindCommandParser --> NpcTrackParser : name
deactivate FindCommandParser
'Hidden arrow to position the destroy marker below the end of the activation bar.`
FindCommandParser -[hidden]-> NpcTrackParser
destroy FindCommandParser

NpcTrackParser --> LogicManager : name
deactivate NpcTrackParser

LogicManager -> FindCommand : execute()
activate FindCommand

FindCommand -> Model : updateFilteredPersonList(predicate)
activate Model

Model --> FindCommand
deactivate Model

create CommandResult
FindCommand -> CommandResult
activate CommandResult

CommandResult --> FindCommand
deactivate CommandResult

FindCommand --> LogicManager : result
deactivate FindCommand

[<--LogicManager
deactivate LogicManager
@enduml
