@startuml
'https://plantuml.com/activity-diagram-beta

start
:User inputs attendance;
:npc_track parses attendance by index, tutorial and status;
if () then (Tutorial is valid)
    if() then (Tutorial status is invalid)
        :Error thrown and user is asked to input correct diagram;
        end
    else ()
        :Attendance is marked accordingly;
        :npc_track confirms marking of attendance;
    endif
else ()
    :Error thrown and user is asked to input correct diagram;
    end
endif

stop

@enduml
